### ISSUE TITLE
support for SVG arcs?

### ISSUE THREAD

**Issue by derhuerst** [stbaer/cardinal-spline#2]
[It seems like the closed cardinal spline of D3.js supports SVG arcs.](https://github.com/d3/d3-shape/blob/04f60b8/test/curve/cardinalClosed-test.js#L11) Therefore, it needs a lot less points to appear smooth. Do you plan to support this?

**Comment by stbaer** [comment]
That looks interesting. But still, adding it here is not something I plan to do. Creating a separate module/repo for it would be better I think.
